# Default values for my-python-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of pod replicas to deploy
replicaCount: 1

image:
  # The repository for the Docker image
  # IMPORTANT: Change this to your Docker Hub username or other registry
  repository: aashishrrjp/my-python-app
  # The policy for pulling the image
  pullPolicy: IfNotPresent
  # The tag of the image to deploy.
  # This should be updated for new versions of your app.
  tag: "1.0.0"

service:
  # The type of Kubernetes service to create
  type: ClusterIP
  # The port the service will listen on
  port: 80

# In a real-world scenario, you would also have sections for:
# ingress:
#   enabled: false
#   hosts:
#     - chart-example.local

# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi
