apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80 # External port for HTTP access
      targetPort: 5000 # Port your Flask app listens on inside the container
  type: LoadBalancer # Exposes your app publicly with a GCP Load Balancer