# This file defines the Kubernetes Deployment object
apiVersion: apps/v1
kind: Deployment
metadata:
  # The name of the deployment is derived from our helper template
  name: {{ include "my-python-app.fullname" . }}
  labels:
    # The labels are also derived from a helper template for consistency
    {{- include "my-python-app.labels" . | nindent 4 }}
spec:
  # The number of replicas is taken from the values.yaml file
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      # This selector must match the labels of the pods created by the template below
      app.kubernetes.io/name: {{ include "my-python-app.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        # These are the labels applied to each pod
        app.kubernetes.io/name: {{ include "my-python-app.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000 # The port our Python app listens on
              protocol: TCP
          # In a real app, you would define liveness and readiness probes here
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
